### PR TITLE
Resolve flake8 errors

### PR DESCRIPTION
**Pull request by mmacy**
Resolve most of the flake8 errors that make sense.

### CODE REVIEW

**Review by johanste — APPROVED** [review]
Please make sure that you format according to black before committing. I don't believe there are any changes needed, but in some cases, flake8 and black are not in agreement (default max line lengths being one example)

Otherwise, looks good.

**Comment by johanste** [comment]
You can also experiment with pydocstyle. Haven't used it myself, so I cannot tell you if it is giving good or bad advice :).

**Comment by mmacy** [comment]
@johanste Will check with black pydocstyle as well, have not used those. I had set line length to 120 (which I ignored on a couple of long comments), is that we're thinking we should adhere to?

**Comment by johanste** [comment]
Black is defaulting to 88. It does not wrap doc comments, though. Black is also nice because it actually formats the code (it doesn't only complain)

**Comment by mmacy** [comment]
@johanste If you've got changes inbound, I'm happy to bail on this PR for now. You can flake8/black/PyDocstyle in your PR if you got things already in-process. Lemme know and I'll close this, if desired.

**Comment by mmacy** [comment]
@johanste Gonna close this one, I'll revisit after we get your changes from #10 merged in.

**Pull request closed without merging**
